{% set name = "ogs5py" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98fb1abf0ec8574150a14714f6b9e7861864b3a480fdb74893d5b83273413e82

build:
  noarch: python
  number: 0
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=41.0.1
    - setuptools_scm >=3.5
  run:
    - python >=3.5
    - numpy >=1.14.5
    - pandas >=0.23.2
    - meshio >=4.0.3,<5.0
    - lxml >=4.0,<5.0
    - pexpect >=4.0,<5.0
    - vtk >=8.1

test:
  imports:
    - ogs5py

about:
  home: https://github.com/GeoStat-Framework/ogs5py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'ogs5py: a python API for OpenGeoSys5'
  description: 'ogs5py: a python API for OpenGeoSys5'
  doc_url: https://geostat-framework.readthedocs.io/projects/ogs5py/
  dev_url: https://github.com/GeoStat-Framework/ogs5py

extra:
  recipe-maintainers:
    - MuellerSeb
